### ISSUE TITLE
cordova.InAppBrowser.open don't work on second and following app starts IOS

### ISSUE THREAD

**Issue by paknecht** [apache/cordova-plugin-inappbrowser#443]
# Bug Report

## Problem
I upgraded Cordova from 7 to 8.1.2 and cordova-ios from 4.5.5 to 5.0.0 and now the inAppBrowser don't work as expected.

### What is expected to happen?
The inAppBrowser should always open the specified URL.

### What does actually happen?
I'm installing the APP.
The app is opened, it starts, then I open the inAppBrowser. The specified URL is loaded. 

I close the app so that it is no longer active in the background. 
I open the app again, it starts, then I open the inAppBrowser. The specified URL is not loaded. Only about:blank is displayed. This behavior will remain until I delete and reinstall the app

## Information
I am currently installing the plugin from the master branch. But it doesn't work on the 3.0.0 either.
This is how I open the inAppBrowser
` var options = "location=no,clearcache=yes,clearsessioncache=yes,zoom=no,hardwareback=yes"`
`var ref = cordova.InAppBrowser.open(encodeURI(myurl), '_blank', options);`

I don't know if you need more Information, I can also provide a video if necessary. 

### Command or Code
See above

### Environment, Platform, Device
It only happens on ios. 
I'm testing on an iPhone X, IOS 12.1

### Version information
Cordova CLI: 8.1.2
Cordova IOS: 5.0.0
Xcode 10.1

Other Plugins i use:
cordova-plugin-splashscreen 
cordova-plugin-statusbar
cordova-plugin-network-information
cordova-plugin-file
cordova-cookie-master
cordova-plugin-cache
cordova-jailbreak-check
phonegap-plugin-push
cordova-plugin-file-opener2
cordova-plugin-blurry-privacy-screen
anyline-document-snapper
cordova-diagnostic-plugin
cordova-plugin-nativestorage

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by paknecht** [comment]
So after a lot of debugging and Google I found the cause of this issue. And it is already fixed but not released.
https://github.com/apache/cordova-ios/issues/447

**Comment by dijashub** [comment]
@paknecht  irrespective of sequence of executing as in @apache/cordova-ios#447

 the issue still same.

**Comment by nathanrobb** [comment]
Fix was released in `cordova-ios 5.0.1`, this issue can likely be closed now?
